/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-04-27 04:11:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <title>NetProphet-dashboard</title>\n");
      out.write("\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/favicon.png\" type=\"image/png\">\n");
      out.write("    <link rel=\"icon\" href=\"images/favicon.png\" type=\"image/png\">\n");
      out.write("\n");
      out.write("    <!-- Bootstrap core CSS -->\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <!-- Custom styles for this template -->\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"//cdn.bootcss.com/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("    <nav class=\"navbar navbar-defualt navbar-fixed-top navbar-header\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <a class=\"col-md-2 col-md-offset-1 navbar-brand\" href=\"#\">NetProphet</a>\n");
      out.write("           <div id=\"navbar\" class=\"navbar-collapse collapse\">\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("              <li><a href=\"#\">Help</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-3 col-sm-4 sidebar\" id=\"scrollbar-side\">\n");
      out.write("          <div>\n");
      out.write("            <h3 class=\"overview\">\n");
      out.write("              <a class=\"selectable\" href=\"#\"><p>Overview</p></a><br/>\n");
      out.write("            </h3>\n");
      out.write("          </div>\n");
      out.write("          <hr/>\n");
      out.write("            <div>\n");
      out.write("              <div class=\"url-list pull-left\">\n");
      out.write("                <h3><a>Url List</a></h3>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"sortby-selector pull-right\">\n");
      out.write("                <span class=\"inline\">Sort by</span>\n");
      out.write("                <select>\n");
      out.write("                  <option>URL ASC</option>\n");
      out.write("                  <!-- <option>overallDelay DESC</option> -->\n");
      out.write("                  <!-- <option>dnsDelay DESC</option> -->\n");
      out.write("                </select>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("            <div class=\"clearfix\"></div>\n");
      out.write("            <ul class=\"nav nav-sidebar\"></ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-9 col-md-offset-3 col-sm-8 col-sm-offset-4 main\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-md-12 col-sm-12 card-title\">\n");
      out.write("              <h2>WIFI</h2>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"wifi-content\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-12 col-sm-12 card-title\">\n");
      out.write("              <h2>Mobile</h2>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"mobile-content\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Bootstrap core JavaScript\n");
      out.write("    ================================================== -->\n");
      out.write("\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("      var application=\"");
      out.print(request.getParameter("application"));
      out.write("\";\n");
      out.write("    </script>\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"js/highcharts.js\"></script>\n");
      out.write("    <script src=\"js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"js/dashboard.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("      var url = \"baidu.com\";\n");
      out.write("      function getSortByContent() {\n");
      out.write("        var sortByContent=\"url\";\n");
      out.write("        return sortByContent;\n");
      out.write("      }\n");
      out.write("      // var X= $.post(\"ChartServlet\",{data:url}, function(data) {drawLineChart(data);});\n");
      out.write("    </script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
